// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzlumQ2sqewgq0rS1CJIwv4tGFw7h9V0',
    appId: '1:902007042623:web:b882049a0961015668be8a',
    messagingSenderId: '902007042623',
    projectId: 'deliveryapp-f93a5',
    authDomain: 'deliveryapp-f93a5.firebaseapp.com',
    storageBucket: 'deliveryapp-f93a5.appspot.com',
    measurementId: 'G-ECSLKSQXCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHY-uxf6P_mNnji5SpgcZ_21PCLRV7blk',
    appId: '1:902007042623:android:18307bf4d338f82b68be8a',
    messagingSenderId: '902007042623',
    projectId: 'deliveryapp-f93a5',
    storageBucket: 'deliveryapp-f93a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxhatMNAYpCkQFVS0HsrEOqeet4D60uAI',
    appId: '1:902007042623:ios:c0af9560c284ecd168be8a',
    messagingSenderId: '902007042623',
    projectId: 'deliveryapp-f93a5',
    storageBucket: 'deliveryapp-f93a5.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxhatMNAYpCkQFVS0HsrEOqeet4D60uAI',
    appId: '1:902007042623:ios:5ea6428332a8d27068be8a',
    messagingSenderId: '902007042623',
    projectId: 'deliveryapp-f93a5',
    storageBucket: 'deliveryapp-f93a5.appspot.com',
    iosBundleId: 'com.example.deliveryApp.RunnerTests',
  );
}
